title: Drew Labs 🧪
description: A blog about random ramblings that I have. 🤔
theme: just-the-docs

color_scheme: drewlabs
        
url: https://jdrew1303.github.io

include:
 - _posts
 - _includes
 
search:
    button: false
    rel_url: false